name: STAGE CI CD

on:
  push:
    branches:
    - stage

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.18.0
    - name: Install node dependencies
      run: yarn install
    - name: Run linter
      run: yarn run lint
    - name: Run build task
      run: NODE_ENV=production NEXT_PUBLIC_API_ORIGIN=${{ secrets.NEXT_PUBLIC_API_ORIGIN }} SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} SENTRY_AUTO_RELEASE=true yarn run build
    - name: Upload static assets to cdn's S3
      uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.CDN_AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.CDN_AWS_SECRET_ACCESS_KEY }}
        aws_bucket: ${{ secrets.CDN_AWS_BUCKET }}
        source_dir: '.next/static'
        destination_dir: '_next/static'
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.LINODE_SSH_PRIVACY_KEY }}
          ARGS: "-rltgoDzvO --delete"
          REMOTE_HOST: ${{ secrets.LINODE_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.LINODE_REMOTE_USER }}
          TARGET: ${{ secrets.LINODE_REMOTE_STAGE_TARGET }}
          EXCLUDE: ".github, task-definition--stage.json"
    - name: Reload web server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LINODE_REMOTE_HOST }}
        username: ${{ secrets.LINODE_REMOTE_USER }}
        key: ${{ secrets.LINODE_SSH_PRIVACY_KEY }}
        script: bash reload.sh
